[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
fs_permissions = [
  { access = "read", path = ".env" },
  { access = "write", path = "./script/addresses" },
  { access = "write", path = "./web-ui/src/addresses" } # ✅ Added line
]

[rpc_endpoints]
localhost = "http://localhost:8545"
